// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9zeeKfeMlD0TISCWc_MM_ETG480FTTTw',
    appId: '1:779290087740:web:64fb315f8f704207c84e39',
    messagingSenderId: '779290087740',
    projectId: 'hopehub-e2966',
    authDomain: 'hopehub-e2966.firebaseapp.com',
    storageBucket: 'hopehub-e2966.appspot.com',
    measurementId: 'G-MBEELE6ZQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdilupbzIsRGnOa-LyGvUWI74lOKk7vkY',
    appId: '1:779290087740:android:544fefc7b86fbb1bc84e39',
    messagingSenderId: '779290087740',
    projectId: 'hopehub-e2966',
    storageBucket: 'hopehub-e2966.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeWysreEgf9XDkVj1uUOYM5349JPbmbMM',
    appId: '1:779290087740:ios:9e0e3673a0136d7bc84e39',
    messagingSenderId: '779290087740',
    projectId: 'hopehub-e2966',
    storageBucket: 'hopehub-e2966.appspot.com',
    iosBundleId: 'com.example.hopehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeWysreEgf9XDkVj1uUOYM5349JPbmbMM',
    appId: '1:779290087740:ios:9e0e3673a0136d7bc84e39',
    messagingSenderId: '779290087740',
    projectId: 'hopehub-e2966',
    storageBucket: 'hopehub-e2966.appspot.com',
    iosBundleId: 'com.example.hopehub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9zeeKfeMlD0TISCWc_MM_ETG480FTTTw',
    appId: '1:779290087740:web:6e2188c37be6a6c4c84e39',
    messagingSenderId: '779290087740',
    projectId: 'hopehub-e2966',
    authDomain: 'hopehub-e2966.firebaseapp.com',
    storageBucket: 'hopehub-e2966.appspot.com',
    measurementId: 'G-4NHLGM1MZD',
  );
}
